ENABLED=1
AGGRESSIVE=0
SCANNING_TWEAKS=1
DISPLAY_IDLE_TWEAKS=1
DOZE_TUNING=1
ULTRA_IDLE=0
SCREEN_ON_SAVER=0
HAPTICS_OFF=0
DARK_MODE=0
DARK_WALLPAPER=0
EXPORT_APP_POLICY=1
SCREEN_ON_REFRESH_RATE=60
PROTECTED_PACKAGES=com.android.dialer,com.android.phone,com.android.server.telecom,com.android.providers.telephony,com.android.contacts,com.android.messaging,com.google.android.apps.messaging,com.android.deskclock,com.google.android.deskclock,com.google.android.gms,com.google.android.gsf,com.google.android.ims,com.android.systemui,me.weishu.kernelsu,com.topjohnwu.magisk,org.lsposed.manager
