#!/system/bin/sh
V=1.8.0; D=/sdcard/Download; S=/data/local/tmp/peridot_start.txt
C=/data/local/tmp/peridot_idle.conf; W=/data/local/tmp/peridot_protected.txt
DEF="com.android.dialer com.android.phone com.android.server.telecom com.android.providers.telephony com.android.contacts com.android.messaging com.google.android.apps.messaging com.android.deskclock com.google.android.deskclock com.google.android.gms com.google.android.gsf com.google.android.ims com.android.systemui me.weishu.kernelsu com.topjohnwu.magisk org.lsposed.manager org.telegram.messenger com.google.android.apps.maps"
[ -f "$W" ]||printf "%s\n" $DEF >"$W"
gp(){ settings get "$1" "$2" 2>/dev/null; }; sp(){ settings put "$1" "$2" "$3" >/dev/null 2>&1; }
del(){ settings delete "$1" "$2" >/dev/null 2>&1; }; say(){ echo "$@"; }
status(){ say "Peridot Idle v$V by Mohithash"; for x in "global wifi_scan_always_enabled" "global ble_scan_always_enabled" "global mobile_data_always_on" "secure nearby_scanning_enabled" "secure doze_enabled" "secure doze_always_on" "system haptic_feedback_enabled" "system peak_refresh_rate" "system min_refresh_rate"; do set -- $x; say "$2=$(gp $1 $2)"; done; }
apply(){ sp global wifi_scan_always_enabled 0; sp global ble_scan_always_enabled 0; sp global wifi_wakeup_enabled 0; sp global adaptive_connectivity_enabled 0; sp global mobile_data_always_on 0; sp secure nearby_scanning_enabled 0; sp secure doze_enabled 0; sp secure doze_always_on 0; sp secure doze_pulse_on_pick_up 0; sp secure doze_pulse_on_double_tap 0; sp secure doze_pulse_on_tap 0; sp secure ambient_display_enabled 0; sp secure wake_gesture_enabled 0; sp secure pickup_gesture_enabled 0; sp system haptic_feedback_enabled 0; sp system peak_refresh_rate 60; sp system min_refresh_rate 60; cmd uimode night yes >/dev/null 2>&1; say "Applied safe ultra settings."; status; }
reset(){ sp global wifi_scan_always_enabled 1; sp global ble_scan_always_enabled 1; sp global mobile_data_always_on 1; sp secure doze_enabled 1; sp system haptic_feedback_enabled 1; del system peak_refresh_rate; del system min_refresh_rate; cmd uimode night no >/dev/null 2>&1; rm -f "$C"; say "Reset basic values. Remove module and reboot."; status; }
profile(){ echo "PROFILE=$1" >"$C"; case "$1" in balanced) sp system peak_refresh_rate 90; sp system min_refresh_rate 60;; screen) sp system peak_refresh_rate 60; sp system min_refresh_rate 60; sp system haptic_feedback_enabled 0;; idle|ultra|night|*) apply;; esac; say "Profile $1 applied. Untouched: calls/SMS/Clock/IMS/modem/GMS/SystemUI/root."; }
protected(){ case "$1" in list|"") cat "$W";; add) shift; for p in "$@";do grep -qx "$p" "$W" 2>/dev/null||echo "$p">>"$W";done;; remove) shift; for p in "$@";do grep -vx "$p" "$W">"$W.tmp";mv "$W.tmp" "$W";done;; reset) printf "%s\n" $DEF >"$W";; esac; }
safety(){ say "Safe design: no package freezing/disabling, no appops sweep, no modem/IMS/telephony/GMS/SystemUI stop, no remount, no thermal/governor/wakelock writes."; say "Protected packages:"; cat "$W"; dumpsys alarm 2>/dev/null|grep -m1 -i "next alarm"; }
overnight_start(){ date >"$S"; dumpsys battery|grep level >>"$S"; say "Baseline saved. Sleep 6-8h, then run overnight-report."; }
overnight_report(){ say "Start:"; cat "$S" 2>/dev/null; say "Now:"; dumpsys battery|grep level; say "Run analyze-all for cause hints."; }
wake(){ say "--- wakelocks ---"; cat /sys/kernel/debug/wakeup_sources 2>/dev/null|head -40||cat /d/wakeup_sources 2>/dev/null|head -40; }
alarm(){ say "--- alarms ---"; dumpsys alarm 2>/dev/null|grep -Ei "wakeup|alarm|pending|package"|head -80; }
jobs(){ say "--- jobs ---"; dumpsys jobscheduler 2>/dev/null|grep -Ei "JOB|u0a|standby|ready|pending|sourcePackage"|head -100; }
loc(){ say "--- location ---"; dumpsys location 2>/dev/null|grep -Ei "provider|request|package|uid|active"|head -80; }
sens(){ say "--- sensors ---"; dumpsys sensorservice 2>/dev/null|head -100; }
net(){ say "--- network ---"; dumpsys netstats 2>/dev/null|grep -Ei "iface|uid|mobile|wifi"|head -80; }
idle(){ say "--- deviceidle ---"; dumpsys deviceidle 2>/dev/null|head -90; wake; }
exports(){ mkdir -p "$D"; cp "$W" "$D/peridot_protected_packages.txt"; pm list packages -3 2>/dev/null|cut -d: -f2>"$D/peridot_user_apps.txt"; grep -vxFf "$D/peridot_protected_packages.txt" "$D/peridot_user_apps.txt" 2>/dev/null>"$D/peridot_hail_freeze_candidates.txt"; { echo "Thanox template: screen off -> restrict/freeze non-whitelist."; echo "Maps/payment: unfreeze on foreground, freeze after exit."; echo "Telegram: allow private messages; mute groups/channels/bots inside Telegram."; } >"$D/peridot_thanox_templates.txt"; say "Exports written to $D/peridot_*"; }
backup(){ mkdir -p "$D"; { status; echo "--- protected ---"; cat "$W"; } >"$D/peridot_idle_restore_pack.txt"; say "$D/peridot_idle_restore_pack.txt"; }
case "$1" in boot) apply;; status|logs) status;; apply|my-setup) apply; exports;; set-profile|apply-profile) profile "${2:-ultra}";; balanced|idle|ultra|night|screen) profile "$1";; pause) date -d "+${2:-2} hour" +%s > /data/local/tmp/peridot_pause_until 2>/dev/null; say "Paused";; resume) rm -f /data/local/tmp/peridot_pause_until; say "Resumed";; protected-list) protected list;; protected-add) shift; protected add "$@"; protected list;; protected-remove) shift; protected remove "$@"; protected list;; protected-reset|set-my-whitelist-defaults) protected reset; protected list;; safety-check) safety;; overnight-start) overnight_start;; overnight-report) overnight_report;; diagnose|analyze-all) idle; alarm; jobs; loc; sens; net;; wakelock-report) wake;; alarm-report) alarm;; jobs-report) jobs;; location-report) loc;; sensor-report) sens;; network-report) net;; idle-score) idle;; export-app-policy|export-thanox|export-thanox-templates|export-hail|export-hail-lists|notification-report|export-my-template|export-quick-actions) exports;; export-backup|export-restore-pack) backup;; snapshot-apps|new-apps-report) pm list packages -3 2>/dev/null|cut -d: -f2>"$D/peridot_user_apps.txt"; cat "$D/peridot_user_apps.txt";; reset-all|restore|restore-category) reset;; clear-logs) rm -f /data/local/tmp/peridot_idle_full.sh; say "Cleared rebuilt payload.";; *) say "Commands: status apply my-setup set-profile ultra safety-check overnight-start overnight-report analyze-all wakelock-report alarm-report jobs-report location-report sensor-report network-report export-my-template protected-list/add/remove/reset reset-all";; esac
